### ISSUE TITLE
Missing link to TC53 Liasion Report's slides in July 2019 meeting's notes

### ISSUE THREAD

**Issue by misterdjules** [rwaldron/tc39-notes#122]
@phoddie I was reading the July 2019 meeting's notes, and found that [the link to the TC53 Liason Report's slides is missing.](https://github.com/tc39/tc39-notes/blob/master/meetings/2019-07/july-23.md#tc53-liaison-report) Do you have a link to those slides?

**Comment by phoddie** [comment]
Here's the link: https://www.icloud.com/keynote/0KVOIMUziDvEHgXdwjcyGg03g#tc53_liaison_tc39_-_july_2019
