### ISSUE TITLE
Shane Carr listed in delegates.txt twice

### ISSUE THREAD

**Issue by michaelficarra** [rwaldron/tc39-notes#125]
Shane Carr (@sffc) is listed in [delegates.txt](https://github.com/rwaldron/tc39-notes/blob/ef694d30fbafc281cd63898b11910417bdcc1e71/delegates.txt) twice.

I don't even know what branch this file is on, but it was linked from the draft notes. Ping @mathiasbynens who seems to have committed it.

**Comment by ljharb** [comment]
It's part of #124.

**Comment by sffc** [comment]
My preferred 3-letter abbreviation is `SFC`.  @mathiasbynens

**Comment by michaelficarra** [comment]
The issue is still present after #124 was merged. https://github.com/rwaldron/tc39-notes/blob/c4466ea1977d17a0fa607e3ab9ff63504dba004f/delegates.txt#L258-L259

**Comment by mathiasbynens** [comment]
Please submit a PR that standardizes on one of the abbreviations, and updates the notes throughout the repo accordingly: https://github.com/rwaldron/tc39-notes/blob/master/delegates.txt

**Comment by sffc** [comment]
I made a PR against delegates.txt, https://github.com/tc39/tc39-notes/pull/24

It's infeasible to update the notes globally.  I could probably do it for one delegate like myself, but it doesn't scale to other similar cases, like with Michael Saboff where we've used different abbreviations.  Instead, I made a new section at the bottom listing "deprecated aliases".

I wasn't sure whether to open the PR again the tc39 version of this repo or the rwaldron version.  Maybe I should have made it against the rwaldron version, but the tc39 version came up first when I was looking for the repo.

**Comment by mathiasbynens** [comment]
> like with Michael Saboff where we've used different abbreviations

#124 took care of that, no?

**Comment by sffc** [comment]
I found several more notes files with inconsistent MS/MLS, especially when MS occurred in the body of the line rather than as a "MS:" prefix.  I changed all the occurrences I found through 2016 in #130.

**Comment by rwaldron** [comment]
Michael Saboff was always "MS", which I think was incorrect. I didn't review every change made in #124 because I don't have time.

**Comment by rwaldron** [comment]
I just did a search for "MS:" and the only records are from Matt Sweeney. 

> especially when MS occurred in the body of the line 

I think you saw abbreviations for "Microsoft"

**Comment by mathiasbynens** [comment]
> Michael Saboff was always "MS", which I think was incorrect.

Indeed, MS had already been claimed at the time: https://github.com/rwaldron/tc39-notes/pull/124/commits/8190e2da634a288d12a1166d0c97dba79676c4c0

**Comment by sffc** [comment]
Yeah, there were several inline cases where "MS" meant "Microsoft", but there were also cases where it was referring to the person that weren't caught yet in 8190e2d, which my PR fixed.
