### ISSUE TITLE
What about notes from November TC39 meeting?

### ISSUE THREAD

**Issue by zloirock** [rwaldron/tc39-notes#36]
More than a month have passed.

**Comment by rwaldron** [comment]
I wasn't there

Maybe @ljharb knows what happened to them?

**Comment by ljharb** [comment]
@rwaldron The notes still exist - I was under the impression that you'd copy them over to your repo. Should I prepare a PR?

**Comment by ljharb** [comment]
I'm not sure what normal markdown tricks you use or if you have any easy tools :-/
