### ISSUE TITLE
Stream meetings to the community

### ISSUE THREAD

**Issue by ajwhite** [rwaldron/tc39-notes#58]
I've been thinking about this for a while, and https://github.com/reactjs/core-notes/issues/32 had sparked my interest back up and steered me towards creating an issue here.

It would be very cool, and I'm sure plenty of us in the community would take advantage of this: could you stream/record the TC39 meetings?

**Comment by ljharb** [comment]
While I understand the appeal, there's a number of reasons why this wouldn't be a good idea - the meetings are intentionally private, and the notes are only released after review.

**Comment by ajwhite** [comment]
I can understand that. I assume this is a place where you can freely speak about ideas that might otherwise spark protest within the community. 

Basically, you don't have the peanut gallery giving feedback on important conversations that, while aren't necessarily going to become part of a specification, are ideas that are important to discuss which might become misinterpreted by the community and cause interference with future planning.

**Comment by ajwhite** [comment]
Closing this request based on @ljharb's feedback and @gaearon's reasoning in https://github.com/reactjs/core-notes/issues/32#issuecomment-257282977, which reflects the same concerns that exist here.
