### ISSUE TITLE
Links to notes in the HTML version of the summary pages are incorrect

### ISSUE THREAD

**Issue by TehShrike** [rwaldron/tc39-notes#72]
On summary pages, for example [this one from the 58th meeting](http://rwaldron.github.io/tc39-notes/2017-05_summary.html), the links to discussion notes, like the one to the bigint discussion, point to the wrong address - the bigint discussion notes links to `may-24.md#15iv-bigint-towards-stage-3` when it should point to `2017-05_may-24.html#15iv-bigint-towards-stage-3`.

**Comment by rwaldron** [comment]
Can you fix the summary page and make PR? Thanks!
