### ISSUE TITLE
Infinity

### ISSUE THREAD

**Issue by tomm1996** [rwaldron/tc39-notes#79]
https://github.com/rwaldron/tc39-notes/blob/master/es8/2017-07/jul-26.md#13iib-consider-changing-numberparseint-and-numberparsefloat
> Consider changing Number.parseInt and Number.parseFloat to avoid converting undefined, null, and NaN to string, returning NaN for those three input values. 

While you're at it, `Infinity` should be considered aswell.
`parseInt(Infinity, 36)`
`>1461559270678`

**Comment by ljharb** [comment]
https://github.com/tc39/ecma262/issues/972#issue-249017955 Is a better place and repo to discuss specific spec issues (when this proposal has a repo, that will be the best place)
